version: '3'

services:
  web:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '9400:80'
    depends_on: 
      - app
    volumes: 
      - ./default.conf:/etc/nginx/conf.d/default.conf:delegated
      - .:/var/www/html:delegated
  app:
    build: 
      context: ./php
    container_name: php
    volumes: 
      - .:/var/www/html:delegated
    depends_on: 
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment: 
      MYSQL_DATABASE: partner
      MYSQL_USER: ojisan
      MYSQL_PASSWORD: ojisan
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - "4080:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    build: ./phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=ojisan
      - MYSQL_PASSWORD=ojisan
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "4000:80"
    depends_on:
      - mysql
volumes: 
  mysql-data: