version: 2.1

orbs: 
  aws-s3: circleci/aws-s3@1.0.0

workflows:
  build_test_deploy:
    jobs:
      - deploy2s3:
        steps:
          - aws-s3/sync:
            from: .
            to: "s3://yuruoji-partner-s3"
            overwrite: true
  
