version: 2.1
jobs: 
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    working_directory: ~/works/partner
    steps:
      - checkout 
      - run: cd laravel && composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run: 
         name: テスト
         command: vendor/bin/phpunit



#テストの自動化
  ## 実行環境を選択
  ## コンテナ内に各種必要なパッケージインストール
  ## コマンド /vendortests/phpunit 実行 

#デプロイの自動化

