version: 2
jobs:
  one:
    docker: 
      - image: circleci/php:7.3-node-browsers
    steps: 
      - checkout
      - run: echo "first"
      - run: sleep 10
  two:
    docker:
      - image: circleci/php:7.3-node-browsers
     steps: 
      - checkout
      - run: echo "second"
      - run: sleep 12
workflows:
  version: 2
  one_two:
    jobs:
      - one
      - two
